expected ':' (py_quiz.py, line 55)